### ISSUE TITLE
VLC syntax

### ISSUE THREAD

**Issue by octavioj** [Sparticuz/docker-liveproxy#1]
Installing the container was very easy but when using vlc, what is the syntax for the GUI? It seems that it does not like very much the URL using localhost. I always get MRL error. Thank you.

**Comment by Sparticuz** [comment]
Take a look at https://github.com/Sparticuz/docker-liveproxy/blob/master/test.m3u for an example. Also, see https://github.com/back-to/liveproxy for instructions on setting up URLs
